experiment:
  name: iterate_dummy_classification
  save_dir: output/
data:
  train:
    data_type: image_folder
    data_location: dataset/ception_dummy_classification_dataset
    annotation_type: dummy_classification_json
    annotation_location: dataset/ception_dummy_classification_dataset/labels.json
    batch_size: 2
    transforms:
      Resize:
        size: 256
      RandomHorizontalFlip: {}
      ToTensor: {}
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
