experiment:
  name: faster_rcnn_bdd100k
model:
  name: faster_rcnn
  backbone: resnet50
  num_classes: 10
  pretrained: True
data:
  train:
    dataset: bdd100k
    data_dir: /path/to/bdd100k
    img_size: 800
    batch_size: 2
    num_workers: 2
  val:
    dataset: bdd100k
    data_dir: /path/to/bdd100k
    img_size: 800
    batch_size: 2
    num_workers: 2
utils:
  seed: 42