experiment:
  name: iterate_dummy_classification
  save_dir: output/
model:
  name: faster_rcnn
  backbone: resnet50
  num_classes: 10
  pretrained: True
data:
  dataset_type: classification
  train_dataset: dummy_classifcation
  train_batch_size: 2
  val_dataset: dummy_classification
  val_batch_size: 2
training:
  epochs: 10
  lr: 0.001
  lr_scheduler: step
  optimizer: adam
evaluation:
  metric_name: mAP
utils:
  seed: 42
  device: cuda
