experiment:
  name: iterate_dummy_classification
  save_dir: output/
model:
  name: faster_rcnn
  backbone: resnet50
  num_classes: 10
  pretrained: True
data:
  train:
    data_type: classification_image_folder
    data_location: dataset/ception_dummy_classification_dataset
    annotation_type: dummy_classification_json
    annotation_location: dataset/ception_dummy_classification_dataset/labels.json
    batch_size: 2
training:
  epochs: 10
  lr: 0.001
  lr_scheduler: step
  optimizer: adam
evaluation:
  metric_name: mAP
utils:
  seed: 42
  device: cuda
