name: Ception CI
on:
  pull_request:
  push: 
    branches: [main] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install mypy
    - name: Create venv
      run: |
        python -m venv ./venv/
        source ./venv/bin/activate
    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
    - name: Install project dependencies
      run: |
        poetry install    
    - name: Pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: ruff check
      uses: astral-sh/ruff-action@v2
      with: 
        args: "format --check"
        version: "0.8.4"
    - name: Run mypy
      run: |
        mypy .
