name: Ception CI
on:
  pull_requests:
  push: 
    branches: [main] 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repo
      uses: actions/checkout@v4
    - name: Python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Create venv
      run: |
        python -m venv ./venv/
    - name: Poetry install
      run: |
        poetry install    
    - name: Pylint
      run: |
        pylint $(git ls-files '*.py')
